codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 60%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 5%
       non_code:
         informational: true
         paths:
           - "docs/**"
           - ".github/**"
           - "scripts/**"
           - "config/**"
           - "AGENTS.md"
           - "README.md"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "crates/*/src/main.rs"  # Ignore main entry points
  - "crates/*/tests/**"      # Ignore test code itself
  - "**/*_test.rs"

flags:
  unittests:
    paths:
      - crates/vicaya-core/
      - crates/vicaya-index/
      - crates/vicaya-scanner/
    carryforward: true
